##############################################################
# +--------------------------------------------------------+ #
# |                         Notes                          | #
# +--------------------------------------------------------+ #
##############################################################

# If you receive an error when the loads config, ensure that:
#   - No tabs are present: YAML only allows spaces
#   - Indents are correct: YAML hierarchy is based entirely on indentation
#   - You have a wrong Material | Entity name. Make sure you have the correct one before posting or trying to seek for help.

##############################################################
# +--------------------------------------------------------+ #
# |                        WARNING                         | #
# +--------------------------------------------------------+ #
##############################################################

# Do not use /reload command because it may cause issues when using mine or other plugins.
# If you encounter any issues please use the /stop command to restart your server.

# > If there's not any world you want the plugin to be disabled, change it to: ` disabled-worlds: [] `
# > You can also change `disabled-worlds` to `enabled-worlds` to allow only the specified worlds to use this plugin.
# This is mostly for servers with multiple-worlds such as minigames.

# WARNING: This option will change only when the server is closed/restarted.
# Please use the /stop command to restart your server.
disabled-worlds:
- example1

# WARNING: THIS FILE IS AUTOMATICALLY GENERATED.
# If you modify this file by hand, be aware that A SINGLE MISTYPED CHARACTER CAN CORRUPT THE FILE.
config-version: 1.0

# Set to true to enable holograms when an item has been dropped and has a custom display name.
enable-custom-item-holograms: true

custom-items:
  nitroglycerin:
    item-type: GLOWSTONE_DUST
    item-name: "&3Nitroglycerin"
    item-lore: "&7A medication used for heart failure, high blood|&7 pressure, anal fissures and to treat and prevent chest pain|&7from not enough blood flow to the heart."

  insulin:
    item-type: FIREWORK_STAR
    item-name: "&3Insulin"
    item-lore: "&7Insulin is a protein hormone that is used as|&7a medication to treat high blood glucose."

  alteplase:
    item-type: CHORUS_FRUIT
    item-name: "&3Alteplase"
    item-lore: "&7A thrombolytic drug, used to treat acute myocardial|&7infarctions (heart attacks) and other severe conditions|&7caused by blood clotting by breaking up the blood clots that cause them."

  syringe:
    item-type: BLAZE_ROD
    item-name: "&cSyringe"
    item-lore: "&7Used for cleaning wounds or body cavities, or fitted with a|&7hollow needle for injecting or withdrawing fluids."

  rescue_inhaler:
    item-type: FEATHER
    item-name: "&cRescue Inhaler"
    item-lore: "&7A medical device used for delivering medication into the body|&7via the lungs. It is mainly used in the treatment of asthma|&7and chronic obstructive pulmonary disease."
    item-duration: 120